use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use anyhow::Result;
use ignore::WalkBuilder;

const BASE: &str = r#"# .ignore — generated by ig-autoignore
# Excludes paths from `ig index` / `ig search`. Same syntax as .gitignore.
# Edit freely — re-running ig-autoignore won't overwrite this file unless --force.

# ── always-noise ──
.DS_Store
*.swp
*.swo
*~
.idea/
.vscode/
*.log

# ── binary / generated assets ──
*.lock
*.min.js
*.min.css
*.map
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.pdf
*.zip
*.tar
*.tar.gz
*.tgz
*.7z
*.rar
*.xlsx
*.xls
*.docx
*.doc
*.pptx
*.ppt
*.mp3
*.mp4
*.mov
*.avi
*.webp
*.woff
*.woff2
*.ttf
*.eot
*.otf
*.bin
*.dat
*.db
*.sqlite
*.sqlite3
"#;

const SECTION_NODE: &str = r#"
# ── Node / JS / TS ──
node_modules/
**/node_modules/
.next/
.nuxt/
.turbo/
.svelte-kit/
.cache/
.parcel-cache/
dist/
build/
out/
coverage/
.nyc_output/
storybook-static/
"#;

const SECTION_NEXT: &str = r#"
# ── Next.js ──
.next/
public/build/
.vercel/
"#;

const SECTION_VITE: &str = r#"
# ── Vite ──
dist/
.vite/
"#;

const SECTION_PHP: &str = r#"
# ── PHP / Laravel ──
vendor/
**/vendor/
storage/framework/cache/
storage/framework/sessions/
storage/framework/views/
storage/logs/
bootstrap/cache/
public/build/
public/storage/
.phpunit.result.cache
"#;

const SECTION_RUST: &str = r#"
# ── Rust ──
target/
Cargo.lock
**/target/
"#;

const SECTION_GO: &str = r#"
# ── Go ──
vendor/
bin/
pkg/
"#;

const SECTION_PYTHON: &str = r#"
# ── Python ──
__pycache__/
**/__pycache__/
*.pyc
*.pyo
.venv/
venv/
.tox/
.mypy_cache/
.pytest_cache/
.ruff_cache/
*.egg-info/
build/
dist/
"#;

const SECTION_RUBY: &str = r#"
# ── Ruby ──
.bundle/
vendor/bundle/
"#;

const SECTION_DOCKER: &str = r#"
# ── Docker / infra ──
infra/data/
**/data/
volumes/
"#;

const SECTION_TERRAFORM: &str = r#"
# ── Terraform ──
.terraform/
*.tfstate
*.tfstate.backup
"#;

const TAIL: &str = r#"
# ── tests fixtures volumineuses ──
**/__snapshots__/
**/fixtures/large/
**/*.snap

# ── Custom — add your project-specific rules below ──
"#;

const SKIP_DIRS: &[&str] = &[
    "node_modules",
    "vendor",
    "target",
    ".git",
    ".next",
    "dist",
    "build",
    ".ig",
];

struct Stacks {
    node: bool,
    bun: bool,
    yarn: bool,
    pnpm: bool,
    next: bool,
    vite: bool,
    php: bool,
    laravel: bool,
    rust: bool,
    go: bool,
    python: bool,
    ruby: bool,
    docker: bool,
    terraform: bool,
}

impl Stacks {
    fn none() -> Self {
        Stacks {
            node: false,
            bun: false,
            yarn: false,
            pnpm: false,
            next: false,
            vite: false,
            php: false,
            laravel: false,
            rust: false,
            go: false,
            python: false,
            ruby: false,
            docker: false,
            terraform: false,
        }
    }

    fn has_node_family(&self) -> bool {
        self.node || self.bun || self.yarn || self.pnpm
    }

    fn any(&self) -> bool {
        self.has_node_family()
            || self.next
            || self.vite
            || self.php
            || self.laravel
            || self.rust
            || self.go
            || self.python
            || self.ruby
            || self.docker
            || self.terraform
    }

    fn names(&self) -> Vec<&'static str> {
        let mut v = Vec::new();
        if self.node {
            v.push("node");
        }
        if self.bun {
            v.push("bun");
        }
        if self.yarn {
            v.push("yarn");
        }
        if self.pnpm {
            v.push("pnpm");
        }
        if self.next {
            v.push("next");
        }
        if self.vite {
            v.push("vite");
        }
        if self.php {
            v.push("php");
        }
        if self.laravel {
            v.push("laravel");
        }
        if self.rust {
            v.push("rust");
        }
        if self.go {
            v.push("go");
        }
        if self.python {
            v.push("python");
        }
        if self.ruby {
            v.push("ruby");
        }
        if self.docker {
            v.push("docker");
        }
        if self.terraform {
            v.push("terraform");
        }
        v
    }
}

fn detect_stacks(target: &std::path::Path) -> Stacks {
    let mut s = Stacks::none();

    let walker = WalkBuilder::new(target)
        .max_depth(Some(3))
        .hidden(false)
        .ignore(false)
        .git_ignore(false)
        .build();

    for entry in walker.flatten() {
        let path = entry.path();

        // Skip noise directories
        if path.is_dir()
            && let Some(name) = path.file_name().and_then(|n| n.to_str())
            && SKIP_DIRS.contains(&name)
        {
            continue;
        }

        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n,
            None => continue,
        };

        // Check if any ancestor is a skip dir
        let skip = path.ancestors().skip(1).any(|anc| {
            anc.file_name()
                .and_then(|n| n.to_str())
                .map(|n| SKIP_DIRS.contains(&n))
                .unwrap_or(false)
        });
        if skip {
            continue;
        }

        match name {
            "package.json" => s.node = true,
            "bun.lock" => s.bun = true,
            "yarn.lock" => s.yarn = true,
            "pnpm-lock.yaml" => s.pnpm = true,
            "composer.json" => s.php = true,
            "artisan" => s.laravel = true,
            "Cargo.toml" => s.rust = true,
            "go.mod" => s.go = true,
            "pyproject.toml" | "requirements.txt" => s.python = true,
            "Gemfile" => s.ruby = true,
            "next.config.js" | "next.config.ts" => s.next = true,
            "nuxt.config.ts" => {
                // nuxt maps to node family too
                s.node = true;
            }
            "vite.config.ts" | "vite.config.js" => s.vite = true,
            "angular.json" => {
                // angular maps to node family
                s.node = true;
            }
            "Dockerfile" | "docker-compose.yml" => s.docker = true,
            _ => {
                if name.ends_with(".tf") {
                    s.terraform = true;
                }
            }
        }
    }

    s
}

fn compose_content(stacks: &Stacks) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str(BASE);

    if stacks.has_node_family() {
        out.push_str(SECTION_NODE);
    }
    if stacks.next {
        out.push_str(SECTION_NEXT);
    }
    if stacks.vite {
        out.push_str(SECTION_VITE);
    }
    if stacks.php || stacks.laravel {
        out.push_str(SECTION_PHP);
    }
    if stacks.rust {
        out.push_str(SECTION_RUST);
    }
    if stacks.go {
        out.push_str(SECTION_GO);
    }
    if stacks.python {
        out.push_str(SECTION_PYTHON);
    }
    if stacks.ruby {
        out.push_str(SECTION_RUBY);
    }
    if stacks.docker {
        out.push_str(SECTION_DOCKER);
    }
    if stacks.terraform {
        out.push_str(SECTION_TERRAFORM);
    }
    out.push_str(TAIL);
    out
}

pub fn run_autoignore(path: Option<PathBuf>, force: bool) -> Result<()> {
    let target = match path {
        Some(p) => p,
        None => env::current_dir()?,
    };

    let ignore_file = target.join(".ignore");

    if ignore_file.exists() && !force {
        println!(
            "ig-autoignore: {} already exists (use --force to overwrite)",
            ignore_file.display()
        );
        return Ok(());
    }

    let stacks = detect_stacks(&target);
    let content = compose_content(&stacks);

    // Atomic write: tempfile + rename
    let tmp_path = target.join(".ignore.tmp");
    {
        let mut f = fs::File::create(&tmp_path)?;
        f.write_all(content.as_bytes())?;
        f.flush()?;
    }
    fs::rename(&tmp_path, &ignore_file)?;

    if stacks.any() {
        let names = stacks.names().join(" ");
        println!(
            "ig-autoignore: wrote {} (stacks: {})",
            ignore_file.display(),
            names
        );
    } else {
        println!(
            "ig-autoignore: wrote {} (no stack detected, base rules only)",
            ignore_file.display()
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn tempdir() -> TempDir {
        tempfile::tempdir().expect("failed to create tempdir")
    }

    #[test]
    fn test_node_and_rust_detected() {
        let dir = tempdir();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        fs::write(dir.path().join("Cargo.toml"), "[package]").unwrap();

        run_autoignore(Some(dir.path().to_path_buf()), false).unwrap();

        let content = fs::read_to_string(dir.path().join(".ignore")).unwrap();
        assert!(
            content.contains("# ── Node / JS / TS ──"),
            "missing Node section"
        );
        assert!(content.contains("# ── Rust ──"), "missing Rust section");
    }

    #[test]
    fn test_idempotent_no_force() {
        let dir = tempdir();
        fs::write(dir.path().join("package.json"), "{}").unwrap();

        run_autoignore(Some(dir.path().to_path_buf()), false).unwrap();
        let content1 = fs::read_to_string(dir.path().join(".ignore")).unwrap();

        // Modify the file manually
        fs::write(dir.path().join(".ignore"), "# custom content").unwrap();

        // Second call without --force should NOT overwrite
        run_autoignore(Some(dir.path().to_path_buf()), false).unwrap();
        let content2 = fs::read_to_string(dir.path().join(".ignore")).unwrap();
        assert_eq!(
            content2, "# custom content",
            "idempotent: should not overwrite existing .ignore"
        );
        let _ = content1;
    }

    #[test]
    fn test_force_overwrites() {
        let dir = tempdir();
        fs::write(dir.path().join("package.json"), "{}").unwrap();

        run_autoignore(Some(dir.path().to_path_buf()), false).unwrap();

        // Overwrite with custom content
        fs::write(dir.path().join(".ignore"), "# custom content").unwrap();

        // --force should overwrite
        run_autoignore(Some(dir.path().to_path_buf()), true).unwrap();
        let content = fs::read_to_string(dir.path().join(".ignore")).unwrap();
        assert!(
            content.contains("# ── Node / JS / TS ──"),
            "force: should regenerate .ignore"
        );
    }

    #[test]
    fn test_base_only_no_stack() {
        let dir = tempdir();

        run_autoignore(Some(dir.path().to_path_buf()), false).unwrap();

        let content = fs::read_to_string(dir.path().join(".ignore")).unwrap();
        assert!(content.contains("# .ignore — generated by ig-autoignore"));
        assert!(
            !content.contains("# ── Node"),
            "should not have Node section"
        );
        assert!(
            !content.contains("# ── Rust"),
            "should not have Rust section"
        );
    }
}
